name: Linting

on: push

jobs:
  markdown:
    name: Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: xt0rted/markdownlint-problem-matcher@v1
      - run: npm i
      - run: npm test
