name: Linting

on: push

jobs:
  markdown:
    name: Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i -g markdownlint-cli
      - uses: xt0rted/markdownlint-problem-matcher@v1
      - run: markdownlint **/*.md
